-- MySQL Script generated by MySQL Workbench
-- Sat Apr 26 20:41:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cul_ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cul_ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cul_ampolla` DEFAULT CHARACTER SET utf8 ;
USE `cul_ampolla` ;

-- -----------------------------------------------------
-- Table `cul_ampolla`.`Provedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_ampolla`.`Provedor` (
  `id_Provedor` INT NOT NULL AUTO_INCREMENT,
  `NIF` VARCHAR(9) NOT NULL,
  `Nom` VARCHAR(255) NOT NULL,
  `Direccio` VARCHAR(255) NULL DEFAULT NULL,
  `Telefon` VARCHAR(20) NULL DEFAULT NULL,
  `Fax` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Provedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_ampolla`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_ampolla`.`Marca` (
  `id_Marca` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_ampolla`.`Restricción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_ampolla`.`Restricción` (
  `id_Restricción` INT NOT NULL,
  `id_Marca` INT NOT NULL,
  `id_Provedor` INT NOT NULL,
  PRIMARY KEY (`id_Marca`, `id_Provedor`, `id_Restricción`),
  INDEX `id_Marca_idx` (`id_Marca` ASC) VISIBLE,
  INDEX `id_Provedor_idx` (`id_Provedor` ASC) VISIBLE,
  CONSTRAINT `id_Marca`
    FOREIGN KEY (`id_Marca`)
    REFERENCES `cul_ampolla`.`Marca` (`id_Marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Provedor`
    FOREIGN KEY (`id_Provedor`)
    REFERENCES `cul_ampolla`.`Provedor` (`id_Provedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_ampolla`.`Gafa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_ampolla`.`Gafa` (
  `id_Gafa` INT NOT NULL AUTO_INCREMENT,
  `id_Provedor` INT NOT NULL,
  `id_Marca` INT NOT NULL,
  `Graduacion_Vidrio_Derecho` DECIMAL NULL DEFAULT NULL,
  `Graduacion_Vidrio_Izquierdo` DECIMAL NULL DEFAULT NULL,
  `Tipo_Montura` ENUM('flotante', 'pasta', 'metálica') NOT NULL,
  `Color_Montura` VARCHAR(45) NULL DEFAULT NULL,
  `Color_Vidrio_Derecho` VARCHAR(45) NULL DEFAULT NULL,
  `Color_Vidre_Esquerre` VARCHAR(45) NULL DEFAULT NULL,
  `Precio` DECIMAL NOT NULL,
  PRIMARY KEY (`id_Gafa`),
  INDEX `id_Provedor_idx` (`id_Provedor` ASC) VISIBLE,
  INDEX `id_Marca_idx` (`id_Marca` ASC) VISIBLE,
  CONSTRAINT `id_Provedor`
    FOREIGN KEY (`id_Provedor`)
    REFERENCES `cul_ampolla`.`Restricción` (`id_Provedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Marca`
    FOREIGN KEY (`id_Marca`)
    REFERENCES `cul_ampolla`.`Restricción` (`id_Marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_ampolla`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_ampolla`.`Cliente` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direcion` VARCHAR(300) NOT NULL,
  `Telefono` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha_Registro` DATE NOT NULL,
  `Recomendado_Por` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_Cliente`),
  INDEX `id_Cliente_idx` (`Recomendado_Por` ASC) VISIBLE,
  CONSTRAINT `id_Cliente`
    FOREIGN KEY (`Recomendado_Por`)
    REFERENCES `cul_ampolla`.`Cliente` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_ampolla`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_ampolla`.`Empleado` (
  `id_Empleado` INT NOT NULL AUTO_INCREMENT,
  `NIF` INT NULL DEFAULT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido1` VARCHAR(45) NOT NULL,
  `Apellido2` VARCHAR(45) NOT NULL,
  `Telefono` INT NULL DEFAULT NULL,
  `Correo_Electrónico` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_ampolla`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_ampolla`.`Venta` (
  `id_Venta` INT NOT NULL AUTO_INCREMENT,
  `id_Cliente` INT NULL DEFAULT NULL,
  `id_Empleado` INT NULL DEFAULT NULL,
  `id_gafa` INT NULL DEFAULT NULL,
  `data_de_venta` DATE NULL DEFAULT NULL,
  `Contidad` INT NULL,
  PRIMARY KEY (`id_Venta`),
  INDEX `id_Cliente_idx` (`id_Cliente` ASC) VISIBLE,
  INDEX `id_Empleado_idx` (`id_Empleado` ASC) VISIBLE,
  INDEX `id_gafa_idx` (`id_gafa` ASC) VISIBLE,
  CONSTRAINT `id_Cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `cul_ampolla`.`Cliente` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Empleado`
    FOREIGN KEY (`id_Empleado`)
    REFERENCES `cul_ampolla`.`Empleado` (`id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_gafa`
    FOREIGN KEY (`id_gafa`)
    REFERENCES `cul_ampolla`.`Gafa` (`id_Gafa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
